### ISSUE TITLE
Crash when mouseScrolled

### ISSUE THREAD

**Issue by tp1415926535** [Leawind/Third-Person#136]
> **Burn after reading:** Before submitting this issue, please make sure the mod version you are using matches the Minecraft version.

## When

Select one:

* launch client
* Join a world
* Enter third person
* Some situation : After mouseScrolled.
    * Currently `leawind_third_person-v2.0.9-mc1.20.1-fabric.jar` only supports game version 1.20.1, but my game version is 1.20.4.
    * When I use `leawind_third_person-v2.0.8-beta.5-mc1.20.4-fabric.jar` , everything works fine.

## Crash report

* carsh report online webpage:
[mclo](https://mclo.gs/3xBVgc0)

* files:
[crash-2024-08-03_00.21.52-client.txt](https://github.com/user-attachments/files/16473367/crash-2024-08-03_00.21.52-client.txt)
[2024-08-03-1.log.gz](https://github.com/user-attachments/files/16473370/2024-08-03-1.log.gz)

**Comment by Leawind** [comment]
Because the parameters of the mouse wheel event in the architectury API of 1.20.4 are different from those of 1.20.1. Therefore, the wheel will cause a crash.
For the time being, only version 2.0.8-beta.5 can be used for 1.20.4

因为 1.20.4 的 architectury API 中，鼠标滚轮事件的参数与 1.20.1的不同，所以滚轮会导致崩溃。
1.20.4 暂时只有 2.0.8-beta.5 这个版本能用。
