### ISSUE TITLE
1.20 beta3 bow's aiming point offset

### ISSUE THREAD

**Issue by nanachijiang** [Leawind/Third-Person#56]
When the "rotate with camera when not aming" option is on, aming with bow has a strange offset.

**Comment by nanachijiang** [comment]
beta3也有相同的问题，弓箭落点在准星左下方，关闭该功能后弓箭瞄准没有问题。

**Comment by nanachijiang** [comment]
https://github.com/LEAWIND/Third-Person/assets/149419724/bc1dfbf0-775b-4574-b84e-f7ec0af8cac2

This is what happend when I turn on the option "rotate with camera when not aming"

**Comment by nanachijiang** [comment]
https://github.com/LEAWIND/Third-Person/assets/149419724/ae7ffd49-8597-413e-b9a0-da1be3644666

This is the normal situation when it's off.

**Comment by bubin7766** [comment]
I'm getting this bug regardless of what setting that toggle is at
I also cant seem to mine blocks in third person whenever my crosshair is aimed at them

**Comment by bubin7766** [comment]
For the video i tested with the original third person and yours
What i found was the reticle lined up with the mined block on the original
Although for your mod it is offset to the left like Nanachi's crosshair as seen in their video
https://github.com/LEAWIND/Third-Person/assets/42780000/e0091e8b-2df3-4114-9853-aa60bd794a48

**Comment by Leawind** [comment]
> I'm getting this bug regardless of what setting that toggle is at I also cant seem to mine blocks in third person whenever my crosshair is aimed at them

fixed in 0a82f7e2cac37036e5af786ec3c8c77d06f2277d

**Comment by Leawind** [comment]
试试启用模组资源包，如果启用后就恢复正常了就说明已经修复了
7e3b34f1fbc6ef4cb038d74694a7a28bf2694c11

**Comment by Leawind** [comment]
因为我之前脑子短路在`mods.toml`里加了行 `showAsResourcePack = true`，导致forge版本的模组内置资源包默认不启用。
所以导致翻译文本失效、无法识别弓弩这类自动进入瞄准模式的物品。
参考 https://leawind.github.io/Third-Person/zh-CN/Features/ResourcePack?autolang
<hr>
Because I had a short-circuited in my brain and added `showAsResourcePack = true` in the `mods.toml` file earlier, it caused the default disabling of the built-in resource pack for the Forge version of the mod. As a result, the translated text became ineffective, and items like crossbows, which automatically enter aiming mode, cannot be recognized.

See https://leawind.github.io/Third-Person/zh-CN/Features/ResourcePack?autolang

**Comment by nanachijiang** [comment]
> 试试启用模组资源包，如果启用后就恢复正常了就说明已经修复了 [7e3b34f](https://github.com/LEAWIND/Third-Person/commit/7e3b34f1fbc6ef4cb038d74694a7a28bf2694c11)

启用资源包之后就没问题了，你是对的

**Comment by Leawind** [comment]
duplicate with #52
